//
// File generated by rootcint at Tue Apr  8 14:56:33 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME pdf_dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "pdf_dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void PDFGrid_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void PDFGrid_Dictionary();

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::PDFGrid*)
   {
      ::PDFGrid *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::PDFGrid),0);
      static ::ROOT::TGenericClassInfo 
         instance("PDFGrid", "./pdf.h", 28,
                  typeid(::PDFGrid), DefineBehavior(ptr, ptr),
                  0, &PDFGrid_Dictionary, isa_proxy, 0,
                  sizeof(::PDFGrid) );
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::PDFGrid*)
   {
      return GenerateInitInstanceLocal((::PDFGrid*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::PDFGrid*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void PDFGrid_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::PDFGrid*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
} // end of namespace ROOT for class ::PDFGrid

/********************************************************
* pdf_dict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablepdf_dict();

extern "C" void G__set_cpp_environmentpdf_dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("pdf.h");
  G__cpp_reset_tagtablepdf_dict();
}
#include <new>
extern "C" int G__cpp_dllrevpdf_dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* PDFGrid */
static int G__pdf_dict_403_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 5:
      G__letint(result7, 85, (long) PDFGrid::load(*(string*) libp->para[0].ref, (PDFGrid::PartonType) G__int(libp->para[1])
, (unsigned int) G__int(libp->para[2]), (unsigned int) G__int(libp->para[3])
, (unsigned int) G__int(libp->para[4])));
      break;
   case 4:
      G__letint(result7, 85, (long) PDFGrid::load(*(string*) libp->para[0].ref, (PDFGrid::PartonType) G__int(libp->para[1])
, (unsigned int) G__int(libp->para[2]), (unsigned int) G__int(libp->para[3])));
      break;
   case 3:
      G__letint(result7, 85, (long) PDFGrid::load(*(string*) libp->para[0].ref, (PDFGrid::PartonType) G__int(libp->para[1])
, (unsigned int) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 85, (long) PDFGrid::load(*(string*) libp->para[0].ref, (PDFGrid::PartonType) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 85, (long) PDFGrid::load(*(string*) libp->para[0].ref));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pdf_dict_403_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const PDFGrid*) G__getstructoffset())->operator()((PDFGrid::PartonType) G__int(libp->para[0]), (afloat_t) G__double(libp->para[1])
, (afloat_t) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pdf_dict_403_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const PDFGrid*) G__getstructoffset())->operator()((int) G__int(libp->para[0]), (afloat_t) G__double(libp->para[1])
, (afloat_t) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pdf_dict_403_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const PDFGrid*) G__getstructoffset())->u((afloat_t) G__double(libp->para[0]), (afloat_t) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pdf_dict_403_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const PDFGrid*) G__getstructoffset())->d((afloat_t) G__double(libp->para[0]), (afloat_t) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pdf_dict_403_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const PDFGrid*) G__getstructoffset())->s((afloat_t) G__double(libp->para[0]), (afloat_t) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pdf_dict_403_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const PDFGrid*) G__getstructoffset())->c((afloat_t) G__double(libp->para[0]), (afloat_t) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pdf_dict_403_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const PDFGrid*) G__getstructoffset())->ubar((afloat_t) G__double(libp->para[0]), (afloat_t) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pdf_dict_403_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const PDFGrid*) G__getstructoffset())->dbar((afloat_t) G__double(libp->para[0]), (afloat_t) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pdf_dict_403_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const PDFGrid*) G__getstructoffset())->sbar((afloat_t) G__double(libp->para[0]), (afloat_t) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pdf_dict_403_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const PDFGrid*) G__getstructoffset())->cbar((afloat_t) G__double(libp->para[0]), (afloat_t) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pdf_dict_403_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const PDFGrid*) G__getstructoffset())->g((afloat_t) G__double(libp->para[0]), (afloat_t) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pdf_dict_403_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const PDFGrid*) G__getstructoffset())->get_dx());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pdf_dict_403_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const PDFGrid*) G__getstructoffset())->get_dQ());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pdf_dict_403_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const PDFGrid*) G__getstructoffset())->get_xmin());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pdf_dict_403_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const PDFGrid*) G__getstructoffset())->get_xmax());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pdf_dict_403_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const PDFGrid*) G__getstructoffset())->get_Qmin());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pdf_dict_403_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const PDFGrid*) G__getstructoffset())->get_Qmax());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pdf_dict_403_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const PDFGrid*) G__getstructoffset())->get_nx());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pdf_dict_403_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const PDFGrid*) G__getstructoffset())->get_nQ());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pdf_dict_403_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const string* pobj;
         const string xobj = ((const PDFGrid*) G__getstructoffset())->get_pdfn();
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pdf_dict_403_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const PDFGrid*) G__getstructoffset())->get_isub());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pdf_dict_403_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 68, (long) ((const PDFGrid*) G__getstructoffset())->get_grid_data((PDFGrid::PartonType) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* PDFGrid */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncpdf_dict {
 public:
  G__Sizep2memfuncpdf_dict(): p(&G__Sizep2memfuncpdf_dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncpdf_dict::*p)();
};

size_t G__get_sizep2memfuncpdf_dict()
{
  G__Sizep2memfuncpdf_dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancepdf_dict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablepdf_dict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__pdf_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__pdf_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pdf_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__pdf_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pdf_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__pdf_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__pdf_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pdf_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__pdf_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pdf_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("afloat_t",100,-1,0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<afloat_t>",117,G__get_linked_tagnum(&G__pdf_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::vector<afloat_t> >",117,G__get_linked_tagnum(&G__pdf_dictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<afloat_t> >",117,G__get_linked_tagnum(&G__pdf_dictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__pdf_dictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pdf_dictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__pdf_dictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pdf_dictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double,allocator<double> > >",117,G__get_linked_tagnum(&G__pdf_dictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("grid_t",117,G__get_linked_tagnum(&G__pdf_dictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,G__get_linked_tagnum(&G__pdf_dictLN_PDFGrid));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("row_t",117,G__get_linked_tagnum(&G__pdf_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),0,G__get_linked_tagnum(&G__pdf_dictLN_PDFGrid));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<grid_t>",117,G__get_linked_tagnum(&G__pdf_dictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__pdf_dictLN_reverse_iteratorlEvectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pdf_dictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__pdf_dictLN_reverse_iteratorlEvectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pdf_dictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > > >",117,G__get_linked_tagnum(&G__pdf_dictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,const grid_t*>",117,G__get_linked_tagnum(&G__pdf_dictLN_maplEintcOconstsPvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOconstsPvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,const vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >*>",117,G__get_linked_tagnum(&G__pdf_dictLN_maplEintcOconstsPvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOconstsPvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,const vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >*,less<int> >",117,G__get_linked_tagnum(&G__pdf_dictLN_maplEintcOconstsPvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOconstsPvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* PDFGrid */
static void G__setup_memvarPDFGrid(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__pdf_dictLN_PDFGrid));
   { PDFGrid *p; p=(PDFGrid*)0x1000; if (p) { }
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__pdf_dictLN_PDFGridcLcLPartonType),-1,-2,1,G__FastAllocString(4096).Format("kunknown=%lldLL",(long long)PDFGrid::kunknown).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__pdf_dictLN_PDFGridcLcLPartonType),-1,-2,1,G__FastAllocString(4096).Format("kgluon=%lldLL",(long long)PDFGrid::kgluon).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__pdf_dictLN_PDFGridcLcLPartonType),-1,-2,1,G__FastAllocString(4096).Format("kd=%lldLL",(long long)PDFGrid::kd).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__pdf_dictLN_PDFGridcLcLPartonType),-1,-2,1,G__FastAllocString(4096).Format("ku=%lldLL",(long long)PDFGrid::ku).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__pdf_dictLN_PDFGridcLcLPartonType),-1,-2,1,G__FastAllocString(4096).Format("ks=%lldLL",(long long)PDFGrid::ks).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__pdf_dictLN_PDFGridcLcLPartonType),-1,-2,1,G__FastAllocString(4096).Format("kc=%lldLL",(long long)PDFGrid::kc).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__pdf_dictLN_PDFGridcLcLPartonType),-1,-2,1,G__FastAllocString(4096).Format("kb=%lldLL",(long long)PDFGrid::kb).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__pdf_dictLN_PDFGridcLcLPartonType),-1,-2,1,G__FastAllocString(4096).Format("kdbar=%lldLL",(long long)PDFGrid::kdbar).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__pdf_dictLN_PDFGridcLcLPartonType),-1,-2,1,G__FastAllocString(4096).Format("kubar=%lldLL",(long long)PDFGrid::kubar).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__pdf_dictLN_PDFGridcLcLPartonType),-1,-2,1,G__FastAllocString(4096).Format("ksbar=%lldLL",(long long)PDFGrid::ksbar).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__pdf_dictLN_PDFGridcLcLPartonType),-1,-2,1,G__FastAllocString(4096).Format("kcbar=%lldLL",(long long)PDFGrid::kcbar).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__pdf_dictLN_PDFGridcLcLPartonType),-1,-2,1,G__FastAllocString(4096).Format("kbbar=%lldLL",(long long)PDFGrid::kbbar).data(),0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__pdf_dictLN_PDFGrid),-1,-2,4,"m_instance=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,-1,-1,4,"m_nx=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,-1,-1,4,"m_nQ=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("afloat_t"),-1,4,"m_dlx=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("afloat_t"),-1,4,"m_dlQ=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("afloat_t"),-1,4,"m_lxmax=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("afloat_t"),-1,4,"m_lxmin=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("afloat_t"),-1,4,"m_lQmax=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("afloat_t"),-1,4,"m_lQmin=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__pdf_dictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR),G__defined_typename("vector<grid_t>"),-1,4,"m_data_vec=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__pdf_dictLN_maplEintcOconstsPvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOconstsPvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRmUgRsPgRsPgR),G__defined_typename("map<int,const grid_t*>"),-1,4,"m_grid_map=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__pdf_dictLN_string),-1,-1,4,"m_pdfn=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,-1,-1,4,"m_isub=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarpdf_dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncPDFGrid(void) {
   /* PDFGrid */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__pdf_dictLN_PDFGrid));
   G__memfunc_setup("load",416,G__pdf_dict_403_0_1, 85, G__get_linked_tagnum(&G__pdf_dictLN_PDFGrid), -1, 0, 5, 3, 1, 0, 
"u 'string' - 11 - pdfn i 'PDFGrid::PartonType' - 0 'kunknown' t "
"h - - 0 'NUMXSAMPLES' - h - - 0 'NUMQSAMPLES' - "
"h - - 0 '0' isubset", (char*)NULL, (void*) G__func2void( (PDFGrid* (*)(const string&, PDFGrid::PartonType, unsigned int, unsigned int, unsigned int))(&PDFGrid::load) ), 0);
   G__memfunc_setup("operator()",957,G__pdf_dict_403_0_2, 100, -1, G__defined_typename("afloat_t"), 0, 3, 1, 1, 8, 
"i 'PDFGrid::PartonType' - 0 - t d - 'afloat_t' 0 - x "
"d - 'afloat_t' 0 - Q", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator()",957,G__pdf_dict_403_0_3, 100, -1, G__defined_typename("afloat_t"), 0, 3, 1, 1, 8, 
"i - - 0 - t d - 'afloat_t' 0 - x "
"d - 'afloat_t' 0 - Q", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("u",117,G__pdf_dict_403_0_4, 100, -1, G__defined_typename("afloat_t"), 0, 2, 1, 1, 8, 
"d - 'afloat_t' 0 - x d - 'afloat_t' 0 - Q", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("d",100,G__pdf_dict_403_0_5, 100, -1, G__defined_typename("afloat_t"), 0, 2, 1, 1, 8, 
"d - 'afloat_t' 0 - x d - 'afloat_t' 0 - Q", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("s",115,G__pdf_dict_403_0_6, 100, -1, G__defined_typename("afloat_t"), 0, 2, 1, 1, 8, 
"d - 'afloat_t' 0 - x d - 'afloat_t' 0 - Q", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("c",99,G__pdf_dict_403_0_7, 100, -1, G__defined_typename("afloat_t"), 0, 2, 1, 1, 8, 
"d - 'afloat_t' 0 - x d - 'afloat_t' 0 - Q", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ubar",426,G__pdf_dict_403_0_8, 100, -1, G__defined_typename("afloat_t"), 0, 2, 1, 1, 8, 
"d - 'afloat_t' 0 - x d - 'afloat_t' 0 - Q", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("dbar",409,G__pdf_dict_403_0_9, 100, -1, G__defined_typename("afloat_t"), 0, 2, 1, 1, 8, 
"d - 'afloat_t' 0 - x d - 'afloat_t' 0 - Q", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("sbar",424,G__pdf_dict_403_0_10, 100, -1, G__defined_typename("afloat_t"), 0, 2, 1, 1, 8, 
"d - 'afloat_t' 0 - x d - 'afloat_t' 0 - Q", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("cbar",408,G__pdf_dict_403_0_11, 100, -1, G__defined_typename("afloat_t"), 0, 2, 1, 1, 8, 
"d - 'afloat_t' 0 - x d - 'afloat_t' 0 - Q", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("g",103,G__pdf_dict_403_0_12, 100, -1, G__defined_typename("afloat_t"), 0, 2, 1, 1, 8, 
"d - 'afloat_t' 0 - x d - 'afloat_t' 0 - Q", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_dx",635,G__pdf_dict_403_0_13, 100, -1, G__defined_typename("afloat_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_dQ",596,G__pdf_dict_403_0_14, 100, -1, G__defined_typename("afloat_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_xmin",859,G__pdf_dict_403_0_15, 100, -1, G__defined_typename("afloat_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_xmax",861,G__pdf_dict_403_0_16, 100, -1, G__defined_typename("afloat_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_Qmin",820,G__pdf_dict_403_0_17, 100, -1, G__defined_typename("afloat_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_Qmax",822,G__pdf_dict_403_0_18, 100, -1, G__defined_typename("afloat_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_nx",645,G__pdf_dict_403_0_19, 104, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_nQ",606,G__pdf_dict_403_0_20, 104, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_pdfn",839,G__pdf_dict_403_0_21, 117, G__get_linked_tagnum(&G__pdf_dictLN_string), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_isub",850,G__pdf_dict_403_0_22, 104, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_grid_data",1342,G__pdf_dict_403_0_23, 68, -1, G__defined_typename("afloat_t"), 0, 1, 1, 1, 8, "i 'PDFGrid::PartonType' - 0 - t", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PDFGrid",608,(G__InterfaceMethod) NULL, 105, G__get_linked_tagnum(&G__pdf_dictLN_PDFGrid), -1, 0, 5, 1, 4, 0, 
"u 'string' - 11 - pdfn h - - 0 - - "
"h - - 0 - - h - - 0 - isub "
"i 'PDFGrid::PartonType' - 0 'kunknown' t", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PDFGrid",608,(G__InterfaceMethod) NULL, 105, G__get_linked_tagnum(&G__pdf_dictLN_PDFGrid), -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PDFGrid",608,(G__InterfaceMethod) NULL, 105, G__get_linked_tagnum(&G__pdf_dictLN_PDFGrid), -1, 0, 1, 1, 4, 0, "u 'PDFGrid' - 11 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator=",937,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__pdf_dictLN_PDFGrid), -1, 1, 1, 1, 4, 0, "u 'PDFGrid' - 11 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_ix",640,(G__InterfaceMethod) NULL, 104, -1, -1, 0, 1, 1, 4, 8, "d - 'afloat_t' 0 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_iQ",601,(G__InterfaceMethod) NULL, 104, -1, -1, 0, 1, 1, 4, 8, "d - 'afloat_t' 0 - Q", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("init",436,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 2, 1, 4, 0, 
"i 'PDFGrid::PartonType' - 0 - t U 'vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >' 'PDFGrid::grid_t' 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("lookup",666,(G__InterfaceMethod) NULL, 100, -1, G__defined_typename("afloat_t"), 0, 3, 1, 4, 8, 
"h - - 0 - ix h - - 0 - iQ "
"U 'vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >' 'PDFGrid::grid_t' 10 - -", (char*)NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncpdf_dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalpdf_dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcpdf_dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__pdf_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__pdf_dictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__pdf_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__pdf_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__pdf_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__pdf_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__pdf_dictLN_PDFGrid = { "PDFGrid" , 99 , -1 };
G__linked_taginfo G__pdf_dictLN_PDFGridcLcLPartonType = { "PDFGrid::PartonType" , 101 , -1 };
G__linked_taginfo G__pdf_dictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR = { "vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >" , 99 , -1 };
G__linked_taginfo G__pdf_dictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__pdf_dictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR = { "vector<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >,allocator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > > > >" , 99 , -1 };
G__linked_taginfo G__pdf_dictLN_reverse_iteratorlEvectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >,allocator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__pdf_dictLN_maplEintcOconstsPvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOconstsPvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRmUgRsPgRsPgR = { "map<int,const vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >*,less<int>,allocator<pair<const int,const vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >*> > >" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablepdf_dict() {
  G__pdf_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__pdf_dictLN_string.tagnum = -1 ;
  G__pdf_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__pdf_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__pdf_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__pdf_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__pdf_dictLN_PDFGrid.tagnum = -1 ;
  G__pdf_dictLN_PDFGridcLcLPartonType.tagnum = -1 ;
  G__pdf_dictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR.tagnum = -1 ;
  G__pdf_dictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__pdf_dictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__pdf_dictLN_reverse_iteratorlEvectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__pdf_dictLN_maplEintcOconstsPvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOconstsPvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRmUgRsPgRsPgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablepdf_dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__pdf_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__pdf_dictLN_string);
   G__get_linked_tagnum_fwd(&G__pdf_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__pdf_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__pdf_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__pdf_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__pdf_dictLN_PDFGrid),sizeof(PDFGrid),-1,36608,(char*)NULL,G__setup_memvarPDFGrid,G__setup_memfuncPDFGrid);
   G__get_linked_tagnum_fwd(&G__pdf_dictLN_PDFGridcLcLPartonType);
   G__get_linked_tagnum_fwd(&G__pdf_dictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__pdf_dictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__pdf_dictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__pdf_dictLN_reverse_iteratorlEvectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__pdf_dictLN_maplEintcOconstsPvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOconstsPvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRmUgRsPgRsPgR);
}
extern "C" void G__cpp_setuppdf_dict(void) {
  G__check_setup_version(30051515,"G__cpp_setuppdf_dict()");
  G__set_cpp_environmentpdf_dict();
  G__cpp_setup_tagtablepdf_dict();

  G__cpp_setup_inheritancepdf_dict();

  G__cpp_setup_typetablepdf_dict();

  G__cpp_setup_memvarpdf_dict();

  G__cpp_setup_memfuncpdf_dict();
  G__cpp_setup_globalpdf_dict();
  G__cpp_setup_funcpdf_dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncpdf_dict();
  return;
}
class G__cpp_setup_initpdf_dict {
  public:
    G__cpp_setup_initpdf_dict() { G__add_setup_func("pdf_dict",(G__incsetup)(&G__cpp_setuppdf_dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initpdf_dict() { G__remove_setup_func("pdf_dict"); }
};
G__cpp_setup_initpdf_dict G__cpp_setup_initializerpdf_dict;

